sudo: required

language: go

go:
- 1.9

services:
  - docker

before_install:
- go get -u github.com/Masterminds/glide/...
- go get -u github.com/golang/lint/golint
- docker run -d --name mdb mongo:3
- docker run -d --name es elasticsearch:2 elasticsearch -Des.cluster.name="graylog"
- docker run -d --name gl --link mdb:mongo --link es:elasticsearch -p 127.0.0.1:9000:9000 graylog/graylog
- docker ps -a

env:
- GRAYLOG_SERVER_URL=http://127.0.0.1:9000/ GRAYLOG_USERNAME=admin GRAYLOG_PASSWORD=admin

script:
- make install
- make testacc
